### PR TITLE
fix: await Environment.lookup (#132)

### PR DESCRIPTION
**Pull request by cpa-gecko**
Environment.lookup seems to return a promise now, i suggest to await the result to fix the error in #132

### CODE REVIEW

**Comment by vobu** [comment]
I've made some minor changes in my local copy of the PR... @cpa-gecko, could you please grant me `rw` on your fork so I can push to it? Thanks!

**Comment by vobu** [comment]
To add some more context: the issue of the async `env.lookup()` stems from `yeoman-environment`^4. In ^3 it's still a sync function.

Yet I could not reproduce the bug from the issues described in #132
* both node 18 + 20 worked flawlessly out of the box for me with a vanilla `yo easy-ui5 project` and `yo easy-ui5 --plugins`
* I searched through the UI5-related (sub-)generators for `yeoman-environment`^4, but all are on ^3
So my guesstimate is that the people affected by #132 must have gotten the module dependency `yeoman-environment`^4 through some other channel.

Anyway, adding an `async` to `env.lookup` will IMO do no harm as it
* will fix #132 when `yeoman-environment` is at ^4
* will only advance the node event loop for `yeoman-environment`^3

**Review by vobu — APPROVED** [review]

**Comment by vobu** [comment]
ready for review @fleischr - and for your approval as well @petermuessig ;)

**Comment by petermuessig** [comment]
As this is compatible also with older version of `yeoman-environment` I'm fine with it and will immediately release a patch for the fix

**Review by petermuessig — APPROVED** [review]

**Comment by petermuessig** [comment]
@cpa-gecko @fleischr @vobu - thanks for following-up on this!

**Comment by petermuessig** [comment]
@cpa-gecko @fleischr @vobu  - one thing which makes me a bit wondering is the min requirement for Node 18.17.0 - many people may have updated but some may have older versions. This comes with the dependency to yeoman-environemnt 4.13.0

**Comment by vobu** [comment]
Node 16 is out of maintenance, substituted by Node 18.
Node 20 is the new LTS.
https://nodejs.org/en/about/previous-releases
That's why `+1 ` from me for >= 18.
(GH Actions now run with Node 20 already)

**Comment by petermuessig** [comment]
It's now >= 18 and not >=18.17 which is OK IMO

https://www.npmjs.com/package/generator-easy-ui5 => 3.7.0 is out

**Comment by cpa-gecko** [comment]
fyi - `yeoman-environment` is installed with global `yo` v5.0.0

see: https://github.com/yeoman/yo/blob/c335710bb74744b2712e4fd80c1190f2650f3b83/package.json#L73

**Pull request merged**
