### PR TITLE
fix: disable autoinstall of Yeoman 5.x

### PR DESCRIPTION
**Pull request by petermuessig**

### CODE REVIEW

**Comment by IObert** [comment]
Thanks Peter. Does this change also affect the other plugins such as generator-ui5-project, generator-ui5-library etc?

**Comment by petermuessig** [comment]
Every generator now runs this install feature at the end (this is the change of Yeoman 5.x). This fixes mainly the first message:

```sh
> ~  % yo easy-ui5

     _-----_     
    |       |    ╭──────────────────────────╮
    |--(o)--|    │  Welcome to the easy-ui5 │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? Select your generator? generator-ui5-ts-app
? How do you want to name this application? (myapp) 
No change to package.json was detected. No package manager install will be executed.
``` 

>> `No change to package.json was detected. No package manager install will be executed.`

This fix avoids this message which is typically logged out after the first question of the sub generator appears and confuses the people. So, yes - it affects all sub generators - but every sub generator should also disable the install of Yeoman 5.x as long as they handle their own install. The good thing: as long as the sub generators stay on Yeoman 4.x there is no problem. In addition, I have to admit, I also don't like the many logs the new install feature of Yeoman 5.x creates - this is annoying and this install feature is not perfectly thought through IMO.

**Comment by IObert** [comment]
> So, yes - it affects all sub generators

So let's include all the other maintainers here:
@vobu @ubheamar @geert-janklaps

**Comment by IObert** [comment]
@petermuessig I understand most of the diff in this [PR](https://github.com/ui5-community/generator-ui5-ts-app/pull/3/files). But I don't understand why you replaced this line with a comment. Is this also related?
```
this.config.set("setupCompleted", true);
```

**Comment by ubheamar** [comment]
> > So, yes - it affects all sub generators
> 
> So let's include all the other maintainers here: @vobu @ubheamar @geert-janklaps

I have made changes in FLP Plugin Repository

**Comment by petermuessig** [comment]
> @petermuessig I understand most of the diff in this [PR](https://github.com/ui5-community/generator-ui5-ts-app/pull/3/files). But I don't understand why you replaced this line with a comment. Is this also related?
> 
> ```
> this.config.set("setupCompleted", true);
> ```

Fixed with: https://github.com/ui5-community/generator-ui5-ts-app/commit/03e8d81b261a83be3d77d46d72a16770f7a83f10

**Comment by vobu** [comment]
> > So, yes - it affects all sub generators
> 
> So let's include all the other maintainers here: @vobu @ubheamar @geert-janklaps

`generator-ui5-project` (which i don't feel to be _the_ maintainer of, but rather _a_ maintainer of 😸) for now stays on yeoman 4.x - so as Peter describes, for the time being no issue here.
But: I'll create an issue in `generator-ui5-project` to make the community aware of this necessary change when switching to yeoman 5

**Comment by IObert** [comment]
Thanks

**Pull request merged**
